//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departamentos()
        {
            this.Empleados = new HashSet<Empleados>();
        }
        
        [Display(Name = "ID Departamento")]
        public int Id_Dep { get; set; }

        [Display(Name = "Departamento")]
        [Required(ErrorMessage ="Debe ingresar un nuevo Departamento.")]
        public string Nombre_Dep { get; set; }

        [Display(Name = "Código")]
        [Required(ErrorMessage = "Debe ingresar un código para el Departamento.")]
        public string Codigo_Dep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
