//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Licencias = new HashSet<Licencias>();
            this.Permisos = new HashSet<Permisos>();
            this.Salidas = new HashSet<Salidas>();
            this.Vacaciones = new HashSet<Vacaciones>();
        }
        
        [Display(Name = "ID")]
        public int Id_Emp { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        public string Apellido { get; set; }

        [Display(Name = "Código")]
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [MinLength(4)]
        [MaxLength(4)]
        public string Codigo_Emp { get; set; }

        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Número de Teléfono no válido.")]
        public long Telefono { get; set; }

        [Display(Name = "Departamento")]
        [Required(ErrorMessage = "Debe seleccionar un Departamento.")]
        public int Departamento_Id { get; set; }

        [Display(Name = "Cargo")]
        [Required(ErrorMessage = "Debe seleccionar un Cargo.")]
        public int Cargo_Id { get; set; }

        [Display(Name = "Fecha Ingreso")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Debe seleccionar una Fecha.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime Fecha_Ingreso { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Range(0, 1000000)]
        public int Salario { get; set; }

        [Required(ErrorMessage = "Debe seleccionar una opción.")]
        public string Estatus { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licencias> Licencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas> Salidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
    }
}
