//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Nomina
    {
        [Display(Name = "ID")]
        public int Id_Nomina { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "Debe ingresar una fecha para la Nomina.")]
        public System.DateTime Fecha { get; set; }

        [Display(Name = "Nómina")]
        [Required(ErrorMessage = "El total de la Nomina debe tener un valor válido.")]
        public int Total { get; set; }
    }
}
