//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Vacaciones
    {
        [Display(Name = "ID Vacaciones")]
        public int Id_Vacaciones { get; set; }

        [Required(ErrorMessage = "Debe seleccionar un Empleado.")]
        public int Empleado { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Debe seleccionar una Fecha.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime Desde { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Debe seleccionar una Fecha.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime Hasta { get; set; }

        public string Comentario { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
